### ISSUE TITLE
[Servlet TCK Challenge]com/sun/ts/tests/servlet/ee/spec/security/runAs assume injected interface loaded in ejb jar first than current web war

### ISSUE THREAD

**Issue by PatrickHuang888** [jakartaee/platform-tck#1176]
**Follow the TCK Process document**
Please follow the instructions in the TCK Process document (https://jakarta.ee/committees/specification/tckprocess) which may be updated occasionally.

**Filing a Challenge**

TCK Challenges MUST be filed via the specification project’s issue tracker using the label challenge and include the following information:

1. The relevant specification version and section number(s).
* Jakarta EE Full Profile TCK 8.0.2
2. The coordinates of the challenged test(s).
jakartaeetck/src/com/sun/ts/tests/servlet/ee/spec/security/runAs
3. The exact TCK version.
* 8.0.2
4. The implementation being tested, including name and company.
* AAS V10, Apusic
5. A full description of why the test is invalid and what the correct behavior is believed to be.
ant version: Apache Ant(TM) version 1.10.9 compiled on September 27 2020
Java version: Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)
this test case has a EJB interface SecTest injected to ServletOne and ServletTwo
```java
public class ServletOne extends HttpServlet {
  @EJB
  SecTest secTest;

public class ServletTwo extends HttpServlet {
  @EJB
  SecTest secTest;

```
and SecTest class be packaged everywhere to 2 test war, ejb jar, and all in 1 ear package like this:
```console
jar tvf jakartaeetck/dist/com/sun/ts/tests/servlet/ee/spec/security/runAs/servlet_ee_spec_security_runAs_ejb.jar
     0 Mon May 22 09:21:02 CST 2023 META-INF/
   424 Mon May 22 09:21:00 CST 2023 META-INF/MANIFEST.MF
     0 Fri Jan 10 06:56:50 CST 2020 com/
     0 Fri Jan 10 06:56:50 CST 2020 com/sun/
     0 Fri Jan 10 06:58:52 CST 2020 com/sun/ts/
     0 Fri Jan 10 06:56:56 CST 2020 com/sun/ts/tests/
     0 Fri Jan 10 06:56:56 CST 2020 com/sun/ts/tests/servlet/
     0 Fri Jan 10 06:56:56 CST 2020 com/sun/ts/tests/servlet/ee/
     0 Fri Jan 10 06:56:56 CST 2020 com/sun/ts/tests/servlet/ee/spec/
     0 Mon May 22 09:20:58 CST 2023 com/sun/ts/tests/servlet/ee/spec/security/
     0 Mon May 22 09:20:58 CST 2023 com/sun/ts/tests/servlet/ee/spec/security/runAs/
   199 Mon May 22 09:20:58 CST 2023 com/sun/ts/tests/servlet/ee/spec/security/runAs/SecTest.class
  1271 Mon May 22 09:20:58 CST 2023 com/sun/ts/tests/servlet/ee/spec/security/runAs/SecTestEJB.class
  1982 Mon May 22 09:20:58 CST 2023 com/sun/ts/tests/servlet/ee/spec/security/runAs/ServletOne.class
  2039 Mon May 22 09:20:58 CST 2023 com/sun/ts/tests/servlet/ee/spec/security/runAs/ServletTwo.class
  1549 Fri Jan 10 06:57:22 CST 2020 META-INF/ejb-jar.xml

jar tvf jakartaeetck/dist/com/sun/ts/tests/servlet/ee/spec/security/runAs/servlet_ee_spec_security_runAs_second_module_web.war
     0 Mon May 22 09:21:02 CST 2023 META-INF/
   424 Mon May 22 09:21:00 CST 2023 META-INF/MANIFEST.MF
     0 Mon May 22 09:21:02 CST 2023 WEB-INF/
     0 Mon May 22 09:21:02 CST 2023 WEB-INF/classes/
     0 Fri Jan 10 06:56:50 CST 2020 WEB-INF/classes/com/
     0 Fri Jan 10 06:56:50 CST 2020 WEB-INF/classes/com/sun/
     0 Fri Jan 10 06:58:52 CST 2020 WEB-INF/classes/com/sun/ts/
     0 Fri Jan 10 06:56:56 CST 2020 WEB-INF/classes/com/sun/ts/tests/
     0 Fri Jan 10 06:56:56 CST 2020 WEB-INF/classes/com/sun/ts/tests/servlet/
     0 Fri Jan 10 06:56:56 CST 2020 WEB-INF/classes/com/sun/ts/tests/servlet/ee/
     0 Fri Jan 10 06:56:56 CST 2020 WEB-INF/classes/com/sun/ts/tests/servlet/ee/spec/
     0 Mon May 22 09:20:58 CST 2023 WEB-INF/classes/com/sun/ts/tests/servlet/ee/spec/security/
     0 Mon May 22 09:20:58 CST 2023 WEB-INF/classes/com/sun/ts/tests/servlet/ee/spec/security/runAs/
   199 Mon May 22 09:20:58 CST 2023 WEB-INF/classes/com/sun/ts/tests/servlet/ee/spec/security/runAs/SecTest.class
  1982 Mon May 22 09:20:58 CST 2023 WEB-INF/classes/com/sun/ts/tests/servlet/ee/spec/security/runAs/ServletOne.class
  2039 Mon May 22 09:20:58 CST 2023 WEB-INF/classes/com/sun/ts/tests/servlet/ee/spec/security/runAs/ServletTwo.class

jar tvf jakartaeetck/dist/com/sun/ts/tests/servlet/ee/spec/security/runAs/servlet_ee_spec_security_runAs_first_module_web.war
     0 Mon May 22 09:21:02 CST 2023 META-INF/
   424 Mon May 22 09:21:00 CST 2023 META-INF/MANIFEST.MF
     0 Mon May 22 09:21:02 CST 2023 WEB-INF/
     0 Mon May 22 09:21:02 CST 2023 WEB-INF/classes/
     0 Fri Jan 10 06:56:50 CST 2020 WEB-INF/classes/com/
     0 Fri Jan 10 06:56:50 CST 2020 WEB-INF/classes/com/sun/
     0 Fri Jan 10 06:58:52 CST 2020 WEB-INF/classes/com/sun/ts/
     0 Fri Jan 10 06:56:56 CST 2020 WEB-INF/classes/com/sun/ts/tests/
     0 Fri Jan 10 06:56:56 CST 2020 WEB-INF/classes/com/sun/ts/tests/servlet/
     0 Fri Jan 10 06:56:56 CST 2020 WEB-INF/classes/com/sun/ts/tests/servlet/ee/
     0 Fri Jan 10 06:56:56 CST 2020 WEB-INF/classes/com/sun/ts/tests/servlet/ee/spec/
     0 Mon May 22 09:20:58 CST 2023 WEB-INF/classes/com/sun/ts/tests/servlet/ee/spec/security/
     0 Mon May 22 09:20:58 CST 2023 WEB-INF/classes/com/sun/ts/tests/servlet/ee/spec/security/runAs/
   199 Mon May 22 09:20:58 CST 2023 WEB-INF/classes/com/sun/ts/tests/servlet/ee/spec/security/runAs/SecTest.class
  1982 Mon May 22 09:20:58 CST 2023 WEB-INF/classes/com/sun/ts/tests/servlet/ee/spec/security/runAs/ServletOne.class
  2039 Mon May 22 09:20:58 CST 2023 WEB-INF/classes/com/sun/ts/tests/servlet/ee/spec/security/runAs/ServletTwo.class
  2685 Fri Jan 10 06:57:22 CST 2020 WEB-INF/web.xml

jar tvf jakartaeetck/dist/com/sun/ts/tests/servlet/ee/spec/security/runAs/servlet_ee_spec_security_runAs.ear
     0 Mon May 22 09:21:02 CST 2023 META-INF/
   424 Mon May 22 09:21:00 CST 2023 META-INF/MANIFEST.MF
 16509 Mon May 22 09:21:02 CST 2023 servlet_ee_spec_security_runAs_client.jar
  5864 Mon May 22 09:21:02 CST 2023 servlet_ee_spec_security_runAs_ejb.jar
  5835 Mon May 22 09:21:02 CST 2023 servlet_ee_spec_security_runAs_first_module_web.war
  5807 Mon May 22 09:21:02 CST 2023 servlet_ee_spec_security_runAs_second_module_web.war
  1807 Fri Jan 10 06:57:22 CST 2020 META-INF/application.xml
```
when testcase ServletOne and ServletTwo loaded, it will load annotation SecTest class, actually SecTest is in the war package also.
Our application server would load class from current package first,  so we load SecTest class from war first, and it's classloader is WarClassLoader, then as EJB SecTest initiated it's loaded from parent EarClassLoader, so when EJB SecTest injected to ServletOne and ServletTwo it has different classloader on SecTest interface, it cannot be inject as SecTest.
The Testcase assume classloader will delegate load class from parent of warclassloader like earclassloader load SecTest from ejb jar in ear, as SecTest loaded from ejb jar, when EJB SecTest initiated, it canbe safelly inject to ServletOne and ServletTwo, becase it's same EarClassloader. I foud Glassfish no error because it delegate classloader to parent.
I think SecTest interface should not packaged everywhere, and it cannot be assumed loaded from parent classloader loaded from EJB as Glassfish do.
6. Any supporting material; debug logs, test output (.jtr file), test logs, run scripts, etc.
```console
[javatest.batch] 05-21-2023 22:13:36:  Sending request "/second_module_cntxt_root/ServletTwoTest"
[javatest.batch] 05-21-2023 22:13:37:  ERROR: Could not access /second_module_cntxt_root/ServletTwoTest
[javatest.batch] 05-21-2023 22:13:37:  ERROR: test failed.
[javatest.batch] 05-21-2023 22:13:37:  ERROR: Caught exception: test failed.
[javatest.batch] 05-21-2023 22:13:37:  ERROR: Test case throws exception: test failed:
[javatest.batch] 05-21-2023 22:13:37:  ERROR: Exception at:
[javatest.batch] 05-21-2023 22:13:37:  ERROR: com.sun.ts.lib.harness.EETest$Fault: test failed.
[javatest.batch]        at com.sun.ts.tests.servlet.ee.spec.security.runAs.Client.web_to_ejb_annotation_runAs(Client.java:229)
[javatest.batch]        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[javatest.batch]        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[javatest.batch]        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javatest.batch]        at java.lang.reflect.Method.invoke(Method.java:498)
[javatest.batch]        at com.sun.ts.lib.harness.EETest.run(EETest.java:596)
[javatest.batch]        at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:486)
[javatest.batch]        at com.sun.ts.lib.harness.EETest.run(EETest.java:337)
[javatest.batch]        at com.sun.ts.lib.harness.EETest.run(EETest.java:285)
[javatest.batch]        at com.sun.ts.tests.servlet.ee.spec.security.runAs.Client.main(Client.java:79)
[javatest.batch]        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[javatest.batch]        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[javatest.batch]        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javatest.batch]        at java.lang.reflect.Method.invoke(Method.java:498)
[javatest.batch]
[javatest.batch] 05-21-2023 22:13:37:  cleanup complete
[javatest.batch] STATUS:Failed.Test case throws exception: test failed:
[javatest.batch] Failed. Test case throws exception: test failed:
[javatest.batch] ********************************************************************************
[javatest.batch] Finished Test:  FAILED........com/sun/ts/tests/servlet/ee/spec/security/runAs/Client.java#web_to_ejb_annotation_runAs
[javatest.batch] ********************************************************************************
[javatest.batch] Number of tests completed:  1 (0 passed, 1 failed, 0 with errors)
[javatest.batch] Number of tests remaining:  1
```
```console
[2023-05-22T10:13:42] [] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=62 _ThreadName=AASLogManager] [timeMillis: 1684721622471] [levelValue: 900] [[
  StandardWrapperValve[ServletOne]: Allocate exception for servlet ServletTwo
java.lang.IllegalArgumentException: Can not set com.sun.ts.tests.servlet.ee.spec.security.runAs.SecTest field com.sun.ts.tests.servlet.ee.spec.security.runAs.ServletTwo.secTest to null value
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
        at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
        at java.lang.reflect.Field.set(Field.java:764)
```

**Comment by scottmarlow** [comment]
I don't understand why the contained ejb jar + war archives cannot have their own copy of SecTest class?

**Comment by PatrickHuang888** [comment]
> I don't understand why the contained ejb jar + war archives cannot have their own copy of SecTest class?

Because SecTest class could be loaded from WarClassloader with ServletOne/ServletTwo together, at the time Injection SecTest stub from EJB that is loaded another ClassLoader which is not `sAssignableFrom`. I have looked into Glassfish which is not throw an error because Glassfish do not load SecTest from WAR it used the parent ClassLoader first load SecTest from EJB.
I donot know if I have described it clearly, If not, I will try  by using ChatGPT to translate for me. :) 

Thanks

**Comment by PatrickHuang888** [comment]
> Can you add server specific descriptor to enable parent first class loading? That is certainly going to be required due to the duplicate classes in this deployment.
> 
> It is not clear why the wars need to bundle the ejb classes in the war. I suspect this is a legacy issue from when the ejb calls were remote.

Yes, I can. Just feel not make sense put class everywhere and pass the test rely on server implemention.

**Comment by scottmarlow** [comment]
@PatrickHuang888 the challenged test could of used a Class-Path reference to the containing archive or used a ear lib.  In the EJB/Platform mailing list discussion, no one has spoken against accepting this challenge and you have been waiting too long.  Please consider your TCK challenge as accepted.

**Comment by scottmarlow** [comment]
Closing as accepted.

**Comment by alwin-joseph** [comment]
@PatrickHuang888 

Can you please confirm if the below tests under jakartaeetck/src/com/sun/ts/tests/servlet/ee/spec/security/runAs is being challenged here ?
- com.sun.ts.tests.servlet.ee.spec.security.runAs.web_to_ejb_dd_runAs
- com.sun.ts.tests.servlet.ee.spec.security.runAs.web_to_ejb_annotation_runAs

We are planning a service release of the Platform TCK and would exclude the challenged tests in the new release.

**Comment by PatrickHuang888** [comment]
> @PatrickHuang888
> 
> Can you please confirm if the below tests under jakartaeetck/src/com/sun/ts/tests/servlet/ee/spec/security/runAs is being challenged here ?
> 
> * com.sun.ts.tests.servlet.ee.spec.security.runAs.web_to_ejb_dd_runAs
> * com.sun.ts.tests.servlet.ee.spec.security.runAs.web_to_ejb_annotation_runAs
> 
> We are planning a service release of the Platform TCK and would exclude the challenged tests in the new release.

Yes, It is.
