### ISSUE TITLE
ejb30/timer/schedule/expire/Client.java#dayOfWeekSunday2 failed when running near daylight saving time

### ISSUE THREAD

**Issue by chengfang** [jakartaee/platform-tck#133]
When running the test (ejb30/timer/schedule/expire/Client.java\#dayOfWeekSunday2_from_ejbliteservlet) one week before switching to or from daylight saving time, this test failed with the following error:

```
Oct 21, 2019 1:40:01 AM com.sun.ts.tests.common.vehicle.ejbliteshare.EJBLiteWebVehicleRunner run
INFO: Connecting http://localhost:8080/ejb30_timer_schedule_expire_ejbliteservlet_vehicle_web/ejbliteservlet_vehicle.jsp?testName=dayOfWeekSunday2
[TEST FAILED] testName=dayOfWeekSunday2 
Created a timer with expression year=* month=* dayOfMonth=* dayOfWeek=7 hour=1 minute=40 second=1 start=Mon Oct 28 01:40:01 EDT 2019 end=null timezone=null
Compare expected nextTimeout Sun Nov 03 01:40:01 EDT 2019, and actual nextTimeout Sun Nov 03 01:40:01 EST 2019

Expecting true, but actual falseRounded dates are not equal; next check if they are close.
Failed with exception 
java.lang.RuntimeException: The time diff 3600000 > 60000
	at com.sun.ts.tests.ejb30.timer.schedule.expire.Client.verifyNextTimeout(Client.java:160)
	at com.sun.ts.tests.ejb30.timer.schedule.expire.Client.dayOfWeek0(Client.java:103)
	at com.sun.ts.tests.ejb30.timer.schedule.expire.Client.dayOfWeekSunday2(Client.java:587)
```

The test tries to verify the next timeout for a scheduled timer that fires every Sunday, by comparing the result of calling `timer.getNextTimeout()`, to a computed expected date.  When computing the expected date, the test does not take into consideration the daylight saving time switch, hence the actual timeout date is +/- 1 hour compared to the expected date.

**Comment by chengfang** [comment]
The following 2 tests also failed for the same reason:

com/sun/ts/tests/ejb30/timer/schedule/expire/Client.java\#dayOfWeekSunday 
com/sun/ts/tests/ejb30/timer/schedule/expire/Client.java\#dayOfWeekAll

**Comment by RohitKumarJain** [comment]
@chengfang , I have raised a PR : https://github.com/eclipse-ee4j/jakartaee-tck/pull/185 

thanks
