### ISSUE TITLE
Refactor jsonb (EE mode) tests.

### ISSUE THREAD

**Issue by starksm64** [jakartaee/platform-tck#1373]

**Comment by alwin-joseph** [comment]
Below are the 2 pending test failures and logs , after the latest changes.

1. com.sun.ts.tests.jsonb.cdi.customizedmapping.adapters.AdaptersCustomizationCDIEjbTest
    Caused by: java.lang.NullPointerException: Cannot invoke "com.sun.ts.tests.jsonb.cdi.customizedmapping.adapters.model.adapter.InjectedAdapter.adaptToJson(com.sun.ts.tests.jsonb.cdi.customizedmapping.adapters.model.Animal)" because "this.animalAdapter" is null
    at com.sun.ts.tests.jsonb.cdi.customizedmapping.adapters.model.adapter.InjectedListAdapter.adaptToJson(InjectedListAdapter.java:40)
    at com.sun.ts.tests.jsonb.cdi.customizedmapping.adapters.model.adapter.InjectedListAdapter.adaptToJson(InjectedListAdapter.java:31)
    at org.eclipse.yasson.internal.serializer.AdapterSerializer.serialize(AdapterSerializer.java:43)
    ... 24 more

2. com.sun.ts.tests.jsonb.cdi.customizedmapping.serializers.SerializersCustomizationCDIEjbTest
    Caused by: java.lang.NullPointerException: Cannot invoke "com.sun.ts.tests.jsonb.cdi.customizedmapping.serializers.model.serializer.AnimalDeserializer.deserialize(jakarta.json.stream.JsonParser, jakarta.json.bind.serializer.DeserializationContext, java.lang.reflect.Type)" because "this.animalDeserializer" is null
    at com.sun.ts.tests.jsonb.cdi.customizedmapping.serializers.model.serializer.AnimalListDeserializerInjected.deserialize(AnimalListDeserializerInjected.java:44)
    at com.sun.ts.tests.jsonb.cdi.customizedmapping.serializers.model.serializer.AnimalListDeserializerInjected.deserialize(AnimalListDeserializerInjected.java:34)

**Comment by alwin-joseph** [comment]
> Below are the 2 pending test failures and logs , after the latest changes.
> 
>     1. com.sun.ts.tests.jsonb.cdi.customizedmapping.adapters.AdaptersCustomizationCDIEjbTest
>        Caused by: java.lang.NullPointerException: Cannot invoke "com.sun.ts.tests.jsonb.cdi.customizedmapping.adapters.model.adapter.InjectedAdapter.adaptToJson(com.sun.ts.tests.jsonb.cdi.customizedmapping.adapters.model.Animal)" because "this.animalAdapter" is null
>        at com.sun.ts.tests.jsonb.cdi.customizedmapping.adapters.model.adapter.InjectedListAdapter.adaptToJson(InjectedListAdapter.java:40)
>        at com.sun.ts.tests.jsonb.cdi.customizedmapping.adapters.model.adapter.InjectedListAdapter.adaptToJson(InjectedListAdapter.java:31)
>        at org.eclipse.yasson.internal.serializer.AdapterSerializer.serialize(AdapterSerializer.java:43)
>        ... 24 more
> 
>     2. com.sun.ts.tests.jsonb.cdi.customizedmapping.serializers.SerializersCustomizationCDIEjbTest
>        Caused by: java.lang.NullPointerException: Cannot invoke "com.sun.ts.tests.jsonb.cdi.customizedmapping.serializers.model.serializer.AnimalDeserializer.deserialize(jakarta.json.stream.JsonParser, jakarta.json.bind.serializer.DeserializationContext, java.lang.reflect.Type)" because "this.animalDeserializer" is null
>        at com.sun.ts.tests.jsonb.cdi.customizedmapping.serializers.model.serializer.AnimalListDeserializerInjected.deserialize(AnimalListDeserializerInjected.java:44)
>        at com.sun.ts.tests.jsonb.cdi.customizedmapping.serializers.model.serializer.AnimalListDeserializerInjected.deserialize(AnimalListDeserializerInjected.java:34)

These 2 Ejb tests in jsonb fail since the jakarta.inject.Inject does not work for them at below locations :

- https://github.com/jakartaee/platform-tck/blob/e3f4fe2fbfa98bc1235c1f600e4c54f8293fdc95/jsonb/src/main/java/com/sun/ts/tests/jsonb/cdi/customizedmapping/adapters/model/adapter/InjectedAdapter.java#L32 
- https://github.com/jakartaee/platform-tck/blob/e3f4fe2fbfa98bc1235c1f600e4c54f8293fdc95/jsonb/src/main/java/com/sun/ts/tests/jsonb/cdi/customizedmapping/adapters/model/adapter/InjectedListAdapter.java#L34 
- https://github.com/jakartaee/platform-tck/blob/e3f4fe2fbfa98bc1235c1f600e4c54f8293fdc95/jsonb/src/main/java/com/sun/ts/tests/jsonb/cdi/customizedmapping/serializers/model/serializer/AnimalDeserializerInjected.java#L38
- https://github.com/jakartaee/platform-tck/blob/e3f4fe2fbfa98bc1235c1f600e4c54f8293fdc95/jsonb/src/main/java/com/sun/ts/tests/jsonb/cdi/customizedmapping/serializers/model/serializer/AnimalListDeserializerInjected.java#L37

When I try to create these objects using `new` , the tests pass, but that would defeat the purpose of test. 
@starksm64 Do you see anything incorrect with the test run setup for these.
