### ISSUE TITLE
Refactor Jakarta Messaging (EE mode) tests

### ISSUE THREAD

**Issue by starksm64** [jakartaee/platform-tck#1495]

**Comment by alwin-joseph** [comment]
Current Status : 

Total Tests : 3510 , Passing: 3318,  Failed: 192

Appclient Tests : 
https://ci.eclipse.org/jakartaee-tck/job/11/job/platform-tck/job/jms-platform-tck-appclient-run
[ERROR] Tests run: 1932, Failures: 0, Errors: 192, Skipped: 0
Logs : https://ci.eclipse.org/jakartaee-tck/job/11/job/platform-tck/job/jms-platform-tck-appclient-run/6/console 

_Failing Tests :_ 
com.sun.ts.tests.jms.ee.ejb.sessionQtests.ClientTest.simpleSendReceiveQueueTest
com.sun.ts.tests.jms.ee.ejb.sessionTtests.ClientTest.simpleSendReceiveT
com.sun.ts.tests.jms.ee.mdb.mdb_exceptQ.ClientTest.*
com.sun.ts.tests.jms.ee.mdb.mdb_exceptT.ClientTest.*
com.sun.ts.tests.jms.ee.mdb.mdb_msgHdrT.ClientTest.*
com.sun.ts.tests.jms.ee.mdb.mdb_msgPropsQ.ClientTest.*
com.sun.ts.tests.jms.ee.mdb.mdb_msgPropsT.ClientTest.*
com.sun.ts.tests.jms.ee.mdb.mdb_msgTypesQ1.ClientTest.*
com.sun.ts.tests.jms.ee.mdb.mdb_msgTypesQ2.ClientTest.*
com.sun.ts.tests.jms.ee.mdb.mdb_msgTypesQ3.ClientTest.*
com.sun.ts.tests.jms.ee.mdb.mdb_msgTypesT1.ClientTest.*
com.sun.ts.tests.jms.ee.mdb.mdb_msgTypesT2.ClientTest.*
com.sun.ts.tests.jms.ee.mdb.mdb_msgTypesT3.ClientTest.*
com.sun.ts.tests.jms.ee.mdb.mdb_rec.ClientTest.*
com.sun.ts.tests.jms.ee.mdb.mdb_sndQ.ClientTest.*
com.sun.ts.tests.jms.ee.mdb.mdb_sndToQueue.ClientTest.*
com.sun.ts.tests.jms.ee.mdb.mdb_sndToTopic.ClientTest.*
com.sun.ts.tests.jms.ee.mdb.mdb_synchrec.ClientTest.*
com.sun.ts.tests.jms.ee.mdb.xa.ClientTest.*
com.sun.ts.tests.jms.ee20.cditests.ejbweb.ClientTest.*
com.sun.ts.tests.jms.ee20.cditests.mdb.ClientTest.*
com.sun.ts.tests.jms.ee20.cditests.usecases.ClientTest.*
com.sun.ts.tests.jms.ee20.ra.activationconfig.queue.selectorauto.annotated.ClientTest.test1
com.sun.ts.tests.jms.ee20.ra.activationconfig.queue.selectorauto.descriptor.ClientTest.test1
com.sun.ts.tests.jms.ee20.ra.activationconfig.queue.selectordups.annotated.ClientTest.test1
com.sun.ts.tests.jms.ee20.ra.activationconfig.queue.selectordups.descriptor.ClientTest.test1
com.sun.ts.tests.jms.ee20.ra.activationconfig.topic.noselnocidautodurable.annotated.ClientTest.test1
com.sun.ts.tests.jms.ee20.ra.activationconfig.topic.noselnocidautodurable.descriptor.ClientTest.test1
com.sun.ts.tests.jms.ee20.ra.activationconfig.topic.selectorautociddurable.annotated.ClientTest.test1
com.sun.ts.tests.jms.ee20.ra.activationconfig.topic.selectorautociddurable.descriptor.ClientTest.test1
com.sun.ts.tests.jms.ee20.ra.activationconfig.topic.selectordupsnondurable.annotated.ClientTest.test1
com.sun.ts.tests.jms.ee20.ra.activationconfig.topic.selectordupsnondurable.descriptor.ClientTest.test1
com.sun.ts.tests.jms.ee20.resourcedefs.annotations.ClientTest.checkClientIDOnDurableConnFactoryTest
com.sun.ts.tests.jms.ee20.resourcedefs.annotations.ClientTest.sendAndRecvQueueTestFromAppClient
com.sun.ts.tests.jms.ee20.resourcedefs.annotations.ClientTest.sendAndRecvQueueTestFromJspClient
com.sun.ts.tests.jms.ee20.resourcedefs.annotations.ClientTest.sendAndRecvTopicTestFromAppClient
com.sun.ts.tests.jms.ee20.resourcedefs.annotations.ClientTest.sendAndRecvTopicTestFromJspClient
com.sun.ts.tests.jms.ee20.resourcedefs.descriptor.ClientAppclientTest.*

JavaTests: 
https://ci.eclipse.org/jakartaee-tck/job/11/job/platform-tck/job/jms-platform-tck-javatest-run
[ERROR] Tests run: 1578, Failures: 0, Errors: 1, Skipped: 0
(The one test failed com/sun/ts/tests/jms/core20/jmscontexttopictests/ClientServletTest#createSharedDurableConsumerTest2. It passes when the suite is run individually.)

**Comment by alwin-joseph** [comment]
> com.sun.ts.tests.jms.ee.mdb.mdb_msgHdrT.ClientTest

Failure logs : 

com.sun.enterprise.container.common.spi.util.InjectionException: Exception attempting to inject Remote ejb-ref name=ejb/MDB_MSGHdrT_Test,Remote 3.x interface =com.sun.ts.tests.jms.commonee.MDB_T_Test,ejb-link=null,lookup=,mappedName=,jndi-name=jms_ee_mdb_mdb_msgHdrT_MDB_MSGHdrT_Test,refType=Session into class com.sun.ts.tests.jms.ee.mdb.mdb_msgHdrT.MDBClient: Lookup failed for java:comp/env/ejb/MDB_MSGHdrT_Test in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl}]
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl._inject(InjectionManagerImpl.java:530)
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.inject(InjectionManagerImpl.java:362)
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.injectClass(InjectionManagerImpl.java:165)
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl.injectClass(InjectionManagerImpl.java:160)
	at org.glassfish.appclient.client.acc.AppClientContainer$ClientMainClassSetting.getClientMainClass(AppClientContainer.java:514)
	at org.glassfish.appclient.client.acc.AppClientContainer.getMainMethod(AppClientContainer.java:425)
	at org.glassfish.appclient.client.acc.AppClientContainer.completePreparation(AppClientContainer.java:335)
	at org.glassfish.appclient.client.acc.AppClientContainer.prepare(AppClientContainer.java:254)
	at org.glassfish.appclient.client.AppClientFacade.prepareACC(AppClientFacade.java:224)
	at org.glassfish.appclient.client.acc.agent.AppClientContainerAgent.premain(AppClientContainerAgent.java:60)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:560)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:572)
Caused by: javax.naming.NamingException: Lookup failed for java:comp/env/ejb/MDB_MSGHdrT_Test in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl}] [Root exception is javax.naming.NameNotFoundException: No object bound for java:comp/env/ejb/MDB_MSGHdrT_Test]
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:836)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:269)
	at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:413)
	at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:565)
	at com.sun.enterprise.container.common.impl.util.InjectionManagerImpl._inject(InjectionManagerImpl.java:470)
	... 13 more
Caused by: javax.naming.NameNotFoundException: No object bound for java:comp/env/ejb/MDB_MSGHdrT_Test
	at com.sun.enterprise.naming.impl.JavaURLContext.lookup(JavaURLContext.java:135)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:818)
	... 17 more
	Suppressed: javax.naming.NamingException: Exception resolving Ejb for 'Remote ejb-ref name=ejb/MDB_MSGHdrT_Test,Remote 3.x interface =com.sun.ts.tests.jms.commonee.MDB_T_Test,ejb-link=null,lookup=,mappedName=,jndi-name=jms_ee_mdb_mdb_msgHdrT_MDB_MSGHdrT_Test,refType=Session' .  Actual (possibly internal) Remote JNDI name used for lookup is 'jms_ee_mdb_mdb_msgHdrT_MDB_MSGHdrT_Test#com.sun.ts.tests.jms.commonee.MDB_T_Test' [Root exception is javax.naming.NamingException: Lookup failed for jms_ee_mdb_mdb_msgHdrT_MDB_MSGHdrT_Test#com.sun.ts.tests.jms.commonee.MDB_T_Test in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl}] [Root exception is javax.naming.NameNotFoundException: jms_ee_mdb_mdb_msgHdrT_MDB_MSGHdrT_Test#com.sun.ts.tests.jms.commonee.MDB_T_Test not found]]
		at com.sun.ejb.EjbNamingReferenceManagerImpl.resolveEjbReference(EjbNamingReferenceManagerImpl.java:159)
		at com.sun.enterprise.container.common.impl.ComponentEnvManagerImpl$EjbReferenceProxy.create(ComponentEnvManagerImpl.java:975)
		at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:621)
		at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:587)
		at com.sun.enterprise.naming.impl.JavaURLContext.lambda$lookup$0(JavaURLContext.java:153)
		at com.sun.enterprise.naming.impl.JavaURLContext.lookupOrCollectException(JavaURLContext.java:550)
		at com.sun.enterprise.naming.impl.JavaURLContext.lookup(JavaURLContext.java:153)
		... 18 more
	Caused by: javax.naming.NamingException: Lookup failed for jms_ee_mdb_mdb_msgHdrT_MDB_MSGHdrT_Test#com.sun.ts.tests.jms.commonee.MDB_T_Test in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl}] [Root exception is javax.naming.NameNotFoundException: jms_ee_mdb_mdb_msgHdrT_MDB_MSGHdrT_Test#com.sun.ts.tests.jms.commonee.MDB_T_Test not found]
		at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:836)
		at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:257)
		at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
		at com.sun.ejb.EjbNamingReferenceManagerImpl.resolveEjbReference(EjbNamingReferenceManagerImpl.java:154)
		... 24 more
	Caused by: javax.naming.NameNotFoundException: jms_ee_mdb_mdb_msgHdrT_MDB_MSGHdrT_Test#com.sun.ts.tests.jms.commonee.MDB_T_Test not found
		at com.sun.enterprise.naming.impl.TransientContext.doLookup(TransientContext.java:234)
		at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:202)
		at com.sun.enterprise.naming.impl.SerialContextProviderImpl.lookup(SerialContextProviderImpl.java:37)
		at com.sun.enterprise.naming.impl.RemoteSerialContextProviderImpl.lookup(RemoteSerialContextProviderImpl.java:85)
		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
		at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie.dispatchToMethod(ReflectiveTie.java:122)
		at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie._invoke(ReflectiveTie.java:152)
		at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatchToServant(ServerRequestDispatcherImpl.java:501)
		at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatch(ServerRequestDispatcherImpl.java:172)
		at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequestRequest(MessageMediatorImpl.java:1529)
		at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequest(MessageMediatorImpl.java:1405)
		at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleInput(MessageMediatorImpl.java:910)
		at com.sun.corba.ee.impl.protocol.giopmsgheaders.RequestMessage_1_2.callback(RequestMessage_1_2.java:192)
		at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequest(MessageMediatorImpl.java:674)
		at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.dispatch(MessageMediatorImpl.java:476)
		at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.doWork(MessageMediatorImpl.java:2202)
		at com.sun.corba.ee.impl.threadpool.ThreadPoolImpl$WorkerThread.performWork(ThreadPoolImpl.java:476)
		at com.sun.corba.ee.impl.threadpool.ThreadPoolImpl$WorkerThread.run(ThreadPoolImpl.java:519)

**Comment by alwin-joseph** [comment]
> com.sun.ts.tests.jms.ee.mdb.mdb_exceptQ.ClientTest.*

Below are from test failure logs for this test:

```
[18:34:50.206] com.sun.mess/SEVERE MQJMSRA_MC4001: constructor:Aborting:JMSException on createConnection=[C4084]: User authorization failed:  user=j2ee, broker=localhost:7676(58966), error code: C4084 
[18:34:50.207] jakarta.ente/WARNING poolmgr.get_connection_failure 
11-19-2024 18:34:50:  ERROR: Test case throws exception: java.lang.Exception: Setup Failed!
11-19-2024 18:34:50:  ERROR: Exception at:  
11-19-2024 18:34:50:  ERROR: java.lang.Exception: Setup Failed!
	at com.sun.ts.tests.jms.commonee.Client.setup(Client.java:164)
	at com.sun.ts.tests.jms.ee.mdb.mdb_exceptQ.MDBClient.setup(MDBClient.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:575)
	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:494)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:348)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:296)
	at com.sun.ts.tests.jms.ee.mdb.mdb_exceptQ.MDBClient.main(MDBClient.java:41)
Caused by: com.sun.messaging.jms.JMSSecurityException: MQRA:CFA:allocation failure:createQueueConnection:MQJMSRA_MC4001: constructor:Aborting:JMSException on createConnection=[C4084]: User authorization failed:  user=j2ee, broker=localhost:7676(58966), error code: C4084
	at com.sun.messaging.jms.ra.ConnectionFactoryAdapter._allocateQueueConnection(ConnectionFactoryAdapter.java:206)
	at com.sun.messaging.jms.ra.ConnectionFactoryAdapter.createQueueConnection(ConnectionFactoryAdapter.java:195)
	at com.sun.ts.tests.jms.commonee.Client.setup(Client.java:149)
	... 10 more
Caused by: jakarta.resource.spi.SecurityException: MQJMSRA_MC4001: constructor:Aborting:JMSException on createConnection=[C4084]: User authorization failed:  user=j2ee, broker=localhost:7676(58966), error code: C4084
	at com.sun.messaging.jms.ra.ManagedConnection.<init>(ManagedConnection.java:148)
	at com.sun.messaging.jms.ra.ManagedConnectionFactory.createManagedConnection(ManagedConnectionFactory.java:185)
	at com.sun.enterprise.resource.allocator.ConnectorAllocator.createResource(ConnectorAllocator.java:145)
	at com.sun.enterprise.resource.pool.ConnectionPool.createSingleResource(ConnectionPool.java:970)
	at com.sun.enterprise.resource.pool.ConnectionPool.createResource(ConnectionPool.java:1248)
	at com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.addResource(RWLockDataStructure.java:78)
	at com.sun.enterprise.resource.pool.ConnectionPool.addResource(ConnectionPool.java:373)
	at com.sun.enterprise.resource.pool.ConnectionPool.createResourceAndAddToPool(ConnectionPool.java:1542)
	at com.sun.enterprise.resource.pool.ConnectionPool.createResources(ConnectionPool.java:1003)
	at com.sun.enterprise.resource.pool.ConnectionPool.initPool(ConnectionPool.java:324)
	at com.sun.enterprise.resource.pool.ConnectionPool.internalGetResource(ConnectionPool.java:567)
	at com.sun.enterprise.resource.pool.ConnectionPool.getResource(ConnectionPool.java:450)
	at com.sun.enterprise.resource.pool.PoolManagerImpl.getResourceFromPool(PoolManagerImpl.java:221)
	at com.sun.enterprise.resource.pool.PoolManagerImpl.getResource(PoolManagerImpl.java:150)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.getResource(ConnectionManagerImpl.java:355)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:298)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:200)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:157)
	at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:151)
	at com.sun.messaging.jms.ra.ConnectionFactoryAdapter._allocateQueueConnection(ConnectionFactoryAdapter.java:204)
	... 12 more
Caused by: com.sun.messaging.jms.JMSSecurityException: [C4084]: User authorization failed:  user=j2ee, broker=localhost:7676(58966)
	at com.sun.messaging.jmq.jmsclient.ProtocolHandler.authenticate(ProtocolHandler.java:929)
	at com.sun.messaging.jmq.jmsclient.ProtocolHandler.hello(ProtocolHandler.java:863)
	at com.sun.messaging.jmq.jmsclient.ProtocolHandler.hello(ProtocolHandler.java:773)
	at com.sun.messaging.jmq.jmsclient.ConnectionImpl.hello(ConnectionImpl.java:512)
	at com.sun.messaging.jmq.jmsclient.ConnectionImpl.openConnection(ConnectionImpl.java:2216)
	at com.sun.messaging.jmq.jmsclient.ConnectionImpl.init(ConnectionImpl.java:1009)
	at com.sun.messaging.jmq.jmsclient.ConnectionImpl.<init>(ConnectionImpl.java:418)
	at com.sun.messaging.jmq.jmsclient.UnifiedConnectionImpl.<init>(UnifiedConnectionImpl.java:32)
	at com.sun.messaging.jmq.jmsclient.XAConnectionImpl.<init>(XAConnectionImpl.java:35)
	at com.sun.messaging.XAConnectionFactory.createXAConnection(XAConnectionFactory.java:76)
	at com.sun.messaging.jms.ra.ManagedConnection.<init>(ManagedConnection.java:143)
	... 31 more
```

**Comment by alwin-joseph** [comment]
> **CDI Tests (Total 25)**
> com.sun.ts.tests.jms.ee20.cditests.ejbweb.ClientTest.*
> com.sun.ts.tests.jms.ee20.cditests.mdb.ClientTest.*
> com.sun.ts.tests.jms.ee20.cditests.usecases.ClientTest.*

@starksm64 These CDI tests are failing with https://github.com/jakartaee/platform-tck/issues/1495#issuecomment-2487686231. Can you please take a look to check if any test setup issue ?

**Comment by kalinchan** [comment]
> > **CDI Tests (Total 25)**
> > com.sun.ts.tests.jms.ee20.cditests.ejbweb.ClientTest.*
> > com.sun.ts.tests.jms.ee20.cditests.mdb.ClientTest.*
> > com.sun.ts.tests.jms.ee20.cditests.usecases.ClientTest.*
> 
> [@starksm64](https://github.com/starksm64) These CDI tests are failing with [#1495 (comment)](https://github.com/jakartaee/platform-tck/issues/1495#issuecomment-2487686231). Can you please take a look to check if any test setup issue ?

These tests are still failing - seems like adding the ejb-ref would solve this.

**Comment by alwin-joseph** [comment]
> > > **CDI Tests (Total 25)**
> > > com.sun.ts.tests.jms.ee20.cditests.ejbweb.ClientTest.*
> > > com.sun.ts.tests.jms.ee20.cditests.mdb.ClientTest.*
> > > com.sun.ts.tests.jms.ee20.cditests.usecases.ClientTest.*
> > 
> > 
> > [@starksm64](https://github.com/starksm64) These CDI tests are failing with [#1495 (comment)](https://github.com/jakartaee/platform-tck/issues/1495#issuecomment-2487686231). Can you please take a look to check if any test setup issue ?
> 
> These tests are still failing - seems like adding the ejb-ref would solve this.

Would you have sample code that uses `ejb-ref` to solve the lookup issue.

**Comment by scottmarlow** [comment]
> > > > **CDI Tests (Total 25)**
> > > > com.sun.ts.tests.jms.ee20.cditests.ejbweb.ClientTest.*
> > > > com.sun.ts.tests.jms.ee20.cditests.mdb.ClientTest.*
> > > > com.sun.ts.tests.jms.ee20.cditests.usecases.ClientTest.*
> > > 
> > > 
> > > [@starksm64](https://github.com/starksm64) These CDI tests are failing with [#1495 (comment)](https://github.com/jakartaee/platform-tck/issues/1495#issuecomment-2487686231). Can you please take a look to check if any test setup issue ?
> > 
> > 
> > These tests are still failing - seems like adding the ejb-ref would solve this.
> 
> Would you have sample code that uses `ejb-ref` to solve the lookup issue.

@alwin-joseph do you happen to have the target output folder for the com.sun.ts.tests.jms.ee20.cditests.ejbweb.ClientTest.* testing?  I'm curious if anything is missing from the cditestsejbweb.ear file.  If you have it locally could you attach the cditestsejbweb.ear file?

**Comment by kalinchan** [comment]
@scottmarlow here is the [ear.zip](https://github.com/user-attachments/files/19394115/ear.zip) file.

**Comment by scottmarlow** [comment]
The same ear in EE 10  has an META-INF/application.xml with contents:

application xmlns="https://jakarta.ee/xml/ns/jakartaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="10" xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/application_10.xsd">
  <description>Application description</description>
  <display-name>cditestsejbweb</display-name>
  <module>
    <java>cditestsejbweb_client.jar</java>
  </module>
  <module>
    <web>
      <web-uri>cditestsejbweb_web.war</web-uri>
      <context-root>cditestsejbweb_web</context-root>
    </web>
  </module>
  <module>
    <ejb>cditestsejbweb_ejb.jar</ejb>
  </module>
</application>

The EE 11 ear.zip that you attached does not contain the application.xml so we are not likely adding that via https://github.com/jakartaee/platform-tck/blob/main/tcks/apis/messaging/messaging-inside-container/src/main/java/com/sun/ts/tests/jms/ee20/cditests/ejbweb/ClientTest.java#L165C15-L165C33

```
            URL earResURL = null;
            earResURL = Client.class.getResource("application.xml.clientear");
            if(earResURL != null) {
              cditestsejbweb_ear.addAsManifestResource(earResURL, "application.xml");
            }
```

^ needs a change

Also, the EE 10 test ear doesn't include the application-client.xml that we are including via https://github.com/jakartaee/platform-tck/blob/main/tcks/apis/messaging/messaging-inside-container/src/main/java/com/sun/ts/tests/jms/ee20/cditests/ejbweb/ClientTest.java#L107C20-L107C42

        // The application-client.xml descriptor
            URL resURL = Client.class.getResource("/com/sun/ts/tests/common/vehicle/appclient/appclient_vehicle_client.xml");
            if(resURL != null) {
              cditestsejbweb_client.addAsManifestResource(resURL, "application-client.xml");
            }

We should try removing the application-client.xml code.

**Comment by scottmarlow** [comment]
I also looked at vehicle.properties from EE 10 which has:
```
com/sun/ts/tests/jms = jms javaee jms_web_profile javaee_web_profile_optional
com/sun/ts/tests/jms/ee20/resourcedefs = jms jms_optional javaee_optional javaee_web_profile_optional
```

So appclient is definitely the wrong protocol to be using for https://github.com/jakartaee/platform-tck/blob/main/tcks/apis/messaging/messaging-inside-container/src/main/java/com/sun/ts/tests/jms/ee20/cditests/ejbweb/ClientTest.java#L58
I think we should be using `javatest` protocol instead.

**Comment by scottmarlow** [comment]
@alwin-joseph should we move https://ci.eclipse.org/jakartaee-tck/job/11/job/work-in-progress/job/messaging-platform-tck-appclient-run/ to https://ci.eclipse.org/jakartaee-tck/job/11/job/tck and run that as part of https://ci.eclipse.org/jakartaee-tck/job/11/job/tck/job/eftl-jakartaeetck-run-full?
