### ISSUE TITLE
Fix Jakarta Persistence missing `Could not find application client` jars

### ISSUE THREAD

**Issue by scottmarlow** [jakartaee/platform-tck#1535]
I ran some of the JPA appclient tests many of which fail with `Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYAC0007: Could not find application client jpa_core_EntityGraph_vehicles_client.jar`.  I let the tests run for an hour before stopping them.  I count around `15000` of these errors in the WildFly appclient.log which I am attaching as [appclient.zip](https://github.com/user-attachments/files/17032922/appclient.zip)

For reference, the packaged jpa_core_EntityGraph_vehicles.ear contains:

tree
.
├── jpa_core_EntityGraph_stateless3_vehicle_client.jar
├── jpa_core_EntityGraph_stateless3_vehicle_ejb.jar
└── lib
    ├── arquillian-core.jar
    ├── arquillian-junit5.jar
    ├── arquillian-protocol-lib-1.0.0-SNAPSHOT.jar
    ├── arquillian-testenricher-cdi-jakarta.jar
    ├── arquillian-testenricher-ejb-jakarta.jar
    ├── arquillian-testenricher-initialcontext.jar
    ├── arquillian-testenricher-msc.jar
    ├── arquillian-testenricher-resource-jakarta.jar
    ├── jpa_core_EntityGraph.jar
    └── wildfly-common-testencricher.jar

More of the appclient.log error output for ^:
```
2024-09-17 10:52:38,140 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0027: Starting deployment of "jpa_core_EntityGraph_vehicles.ear" (runtime-name: "jpa_core_EntityGraph_vehicles.ear")
2024-09-17 10:52:38,196 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-3) MSC000001: Failed to start service jboss.deployment.unit."jpa_core_EntityGraph_vehicles.ear".STRUCTURE: org.jboss.msc.service.StartException in service jboss.deployment.unit."jpa_core_EntityGraph_vehicles.ear".STRUCTURE: WFLYSRV0153: Failed to process phase STRUCTURE of deployment "jpa_core_EntityGraph_vehicles.ear"
        at org.jboss.as.server@26.0.0.Beta1//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:172)
        at org.jboss.msc@1.5.5.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1617)
        at org.jboss.msc@1.5.5.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1580)
        at org.jboss.msc@1.5.5.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1438)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990) 
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486) 
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYAC0007: Could not find application client jpa_core_EntityGraph_vehicles_client.jar
        at org.jboss.as.appclient@34.0.0.Beta1-SNAPSHOT//org.jboss.as.appclient.deployment.ApplicationClientStructureProcessor.deploy(ApplicationClientStructureProcessor.java:69)
        at org.jboss.as.server@26.0.0.Beta1//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:165)
        ... 8 more

2024-09-17 10:52:38,198 ERROR [org.jboss.as.controller.management-operation] (Thread-44) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "jpa_core_EntityGraph_vehicles.ear")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"jpa_core_EntityGraph_vehicles.ear\".STRUCTURE" => "WFLYSRV0153: Failed to process phase STRUCTURE of deployment \"jpa_core_EntityGraph_vehicles.ear\"
    Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYAC0007: Could not find application client jpa_core_EntityGraph_vehicles_client.jar"}}
2024-09-17 10:52:38,199 ERROR [org.jboss.as.controller.management-operation] (Thread-44) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "jpa_core_EntityGraph_vehicles.ear")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"jpa_core_EntityGraph_vehicles.ear\".STRUCTURE" => "WFLYSRV0153: Failed to process phase STRUCTURE of deployment \"jpa_core_EntityGraph_vehicles.ear\"
    Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYAC0007: Could not find application client jpa_core_EntityGraph_vehicles_client.jar"}}
2024-09-17 10:52:38,200 ERROR [org.jboss.as.server] (Thread-44) WFLYSRV0021: Deploy of deployment "jpa_core_EntityGraph_vehicles.ear" was rolled back with the following failure message:
{"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"jpa_core_EntityGraph_vehicles.ear\".STRUCTURE" => "WFLYSRV0153: Failed to process phase STRUCTURE of deployment \"jpa_core_EntityGraph_vehicles.ear\"
    Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYAC0007: Could not find application client jpa_core_EntityGraph_vehicles_client.jar"}}
2024-09-17 10:52:38,202 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-7) WFLYSRV0028: Stopped deployment jpa_core_EntityGraph_vehicles.ear (runtime-name: jpa_core_EntityGraph_vehicles.ear) in 1ms
2024-09-17 10:52:38,204 INFO  [org.jboss.as.server] (Thread-1) WFLYSRV0272: Suspending server

```

**Comment by scottmarlow** [comment]
I'm not sure yet of what is missing exactly.  I'm going to try debugging WildFly running the same ee10 tests and see what I can learn about the difference between ee11 vs ee10 currently.

**Comment by scottmarlow** [comment]
One difference between one of the EE 10 vs 11 deployments:
diff ee11/jpa_core_callback_inheritance_stateless3_vehicle_client/META-INF/application-client.xml ee10/META-INF/application-client.xml
21c21
<   <display-name>stateless3_vehicle_client</display-name>
---
>   <display-name>jpa_core_callback_inheritance_appmanagedNoTx_vehicle_client</display-name>
23c23
<     <ejb-ref-name>ejb/Stateless3VehicleBean</ejb-ref-name>
---
>     <ejb-ref-name>ejb/AppManagedNoTxVehicleBean</ejb-ref-name>
25,26c25,26
<     <remote>com.sun.ts.tests.common.vehicle.stateless3.Stateless3VehicleIF</remote>
<     <ejb-link>Stateless3VehicleBean</ejb-link>
---
>     <remote>com.sun.ts.tests.common.vehicle.appmanagedNoTx.AppManagedNoTxVehicleIF</remote>
>     <ejb-link>AppManagedNoTxVehicleBean</ejb-link>

**Comment by scottmarlow** [comment]
Notes from debugging the appclient deployment with EE 10 + WildFly:

Some debugging state from ApplicationClientStructureProcessor#deploy
```
this = {org.jboss.as.appclient.deployment.ApplicationClientStructureProcessor@10690} 
phaseContext = {org.jboss.as.server.deployment.DeploymentPhaseContextImpl@10691} 
deploymentUnit = {org.jboss.as.server.deployment.DeploymentUnitImpl@10695} "deployment "jpa_core_callback_inheritance_vehicles.ear""
deploymentUnitName = "jpa_core_callback_inheritance_vehicles.ear"
existing = {java.util.HashMap@10707}  size = 11
 {org.jboss.vfs.VirtualFile@10780} ""/content/jpa_core_callback_inheritance_vehicles.ear/lib/jpa_core_callback_inheritance.jar"" -> {org.jboss.as.server.deployment.module.ResourceRoot@10710} "ResourceRoot [root="/content/jpa_core_callback_inheritance_vehicles.ear/lib/jpa_core_callback_inheritance.jar"]"
 {org.jboss.vfs.VirtualFile@10781} ""/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_appmanaged_vehicle_client.jar"" -> {org.jboss.as.server.deployment.module.ResourceRoot@10750} "ResourceRoot [root="/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_appmanaged_vehicle_client.jar"]"
 {org.jboss.vfs.VirtualFile@10782} ""/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_puservlet_vehicle_web.war"" -> {org.jboss.as.server.deployment.module.ResourceRoot@10755} "ResourceRoot [root="/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_puservlet_vehicle_web.war"]"
 {org.jboss.vfs.VirtualFile@10783} ""/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_appmanagedNoTx_vehicle_client.jar"" -> {org.jboss.as.server.deployment.module.ResourceRoot@10745} "ResourceRoot [root="/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_appmanagedNoTx_vehicle_client.jar"]"
 {org.jboss.vfs.VirtualFile@10784} ""/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_stateless3_vehicle_client.jar"" -> {org.jboss.as.server.deployment.module.ResourceRoot@10760} "ResourceRoot [root="/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_stateless3_vehicle_client.jar"]"
 {org.jboss.vfs.VirtualFile@10785} ""/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_stateless3_vehicle_ejb.jar"" -> {org.jboss.as.server.deployment.module.ResourceRoot@10720} "ResourceRoot [root="/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_stateless3_vehicle_ejb.jar"]"
 {org.jboss.vfs.VirtualFile@10786} ""/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_appmanaged_vehicle_ejb.jar"" -> {org.jboss.as.server.deployment.module.ResourceRoot@10715} "ResourceRoot [root="/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_appmanaged_vehicle_ejb.jar"]"
 {org.jboss.vfs.VirtualFile@10787} ""/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_stateful3_vehicle_client.jar"" -> {org.jboss.as.server.deployment.module.ResourceRoot@10725} "ResourceRoot [root="/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_stateful3_vehicle_client.jar"]"
 {org.jboss.vfs.VirtualFile@10788} ""/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_appmanagedNoTx_vehicle_ejb.jar"" -> {org.jboss.as.server.deployment.module.ResourceRoot@10735} "ResourceRoot [root="/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_appmanagedNoTx_vehicle_ejb.jar"]"
 {org.jboss.vfs.VirtualFile@10789} ""/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_pmservlet_vehicle_web.war"" -> {org.jboss.as.server.deployment.module.ResourceRoot@10730} "ResourceRoot [root="/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_pmservlet_vehicle_web.war"]"
 {org.jboss.vfs.VirtualFile@10790} ""/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_stateful3_vehicle_ejb.jar"" -> {org.jboss.as.server.deployment.module.ResourceRoot@10740} "ResourceRoot [root="/content/jpa_core_callback_inheritance_vehicles.ear/jpa_core_callback_inheritance_stateful3_vehicle_ejb.jar"]"
deployment = "jpa_core_callback_inheritance_appmanaged_vehicle_client.jar"
```

**Comment by scottmarlow** [comment]
jpa_core_callback_inheritance_appmanagedNoTx_vehicle_client.jar was also found in EE 10 and deployed successfully in appclient container

**Comment by scottmarlow** [comment]
So on EE 10, we find `jpa_core_callback_inheritance_appmanaged_vehicle_client.jar` + `jpa_core_callback_inheritance_appmanagedNoTx_vehicle_client.jar` in the deployment but in EE 11 we fail to find `jpa_core_EntityGraph_vehicles_client.jar`

**Comment by scottmarlow** [comment]
In EE 10 + 11 source, we have ./com/sun/ts/tests/common/vehicle/appmanaged/appmanaged_vehicle_client.xml:
```
<application-client xmlns="https://jakarta.ee/xml/ns/jakartaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="10" xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/application-client_10.xsd">
  <display-name>appmanaged_vehicle_client</display-name>
  <ejb-ref>
    <ejb-ref-name>ejb/AppManagedVehicleBean</ejb-ref-name>
    <ejb-ref-type>Session</ejb-ref-type>
    <remote>com.sun.ts.tests.common.vehicle.appmanaged.AppManagedVehicleIF</remote>
    <ejb-link>AppManagedVehicleBean</ejb-link>
  </ejb-ref>
</application-client>
```
Will try moving ^ to a place where it can be found by the Persistence tests:

>         renamed:    common/src/main/java/com/sun/ts/tests/common/vehicle/appmanaged/appmanaged_vehicle_client.xml -> jpa/spec-tests/src/main/resources/com/sun/ts/tests/common/vehicle/appmanaged/appmanaged_vehicle_client.xml
>         renamed:    common/src/main/java/com/sun/ts/tests/common/vehicle/appmanaged/appmanaged_vehicle_ejb.jar.sun-ejb-jar.xml -> jpa/spec-tests/src/main/resources/com/sun/ts/tests/common/vehicle/appmanaged/appmanaged_vehicle_ejb.jar.sun-ejb-jar.xml
>

**Comment by scottmarlow** [comment]
Latest failures that we are seeing:

```
2024-09-23 14:35:31,619 INFO  [org.jboss.as.ejb3.deployment] (MSC service thread 1-2) WFLYEJB0473: JNDI bindings for session bean named 'AppManagedVehicleBean' in deployment unit 'subdeployment "jpa_core_EntityGraph_appmanaged_vehicle_client.jar" of deployment "jpa_core_EntityGraph_vehicles.ear"' are as follows:

        java:global/jpa_core_EntityGraph_vehicles/jpa_core_EntityGraph_appmanaged_vehicle_client/AppManagedVehicleBean!com.sun.ts.tests.common.vehicle.appmanaged.AppManagedVehicleIF
        java:app/jpa_core_EntityGraph_appmanaged_vehicle_client/AppManagedVehicleBean!com.sun.ts.tests.common.vehicle.appmanaged.AppManagedVehicleIF
        java:module/AppManagedVehicleBean!com.sun.ts.tests.common.vehicle.appmanaged.AppManagedVehicleIF
        java:jboss/exported/jpa_core_EntityGraph_vehicles/jpa_core_EntityGraph_appmanaged_vehicle_client/AppManagedVehicleBean!com.sun.ts.tests.common.vehicle.appmanaged.AppManagedVehicleIF
        ejb:jpa_core_EntityGraph_vehicles/jpa_core_EntityGraph_appmanaged_vehicle_client/AppManagedVehicleBean!com.sun.ts.tests.common.vehicle.appmanaged.AppManagedVehicleIF?stateful
        java:global/jpa_core_EntityGraph_vehicles/jpa_core_EntityGraph_appmanaged_vehicle_client/AppManagedVehicleBean
        java:app/jpa_core_EntityGraph_appmanaged_vehicle_client/AppManagedVehicleBean
        java:module/AppManagedVehicleBean

2024-09-23 14:35:31,621 WARN  [org.jboss.modules.define] (MSC service thread 1-2) Failed to define class com.sun.ts.tests.common.vehicle.VehicleClient in Module "deployment.jpa_core_EntityGraph_vehicles.ear.jpa_core_EntityGraph_appmanaged_vehicle_client.jar" from Service Module Loader: java.lang.NoClassDefFoundError: Failed to link com/sun/ts/tests/common/vehicle/VehicleClient (Module "deployment.jpa_core_EntityGraph_vehicles.ear.jpa_core_EntityGraph_appmanaged_vehicle_client.jar" from Service Module Loader): com/sun/ts/lib/harness/ServiceEETest
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1105)
        at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:351)
        at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:482)
        at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:276)
        at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:79)
        at org.jboss.modules.Module.loadModuleClass(Module.java:798)
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:192)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:408)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:396)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:115)
        at org.jboss.as.appclient@34.0.0.Beta1-SNAPSHOT//org.jboss.as.appclient.deployment.ApplicationClientManifestProcessor.deploy(ApplicationClientManifestProcessor.java:49)
        at org.jboss.as.server@26.0.0.Beta4//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:165)
        at org.jboss.msc@1.5.5.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1617)
        at org.jboss.msc@1.5.5.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1580)
        at org.jboss.msc@1.5.5.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1438)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: com.sun.ts.lib.harness.ServiceEETest
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at org.jboss.modules.Utils.getSystemClass(Utils.java:179)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:393)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:115)
        ... 22 more

2024-09-23 14:35:31,622 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service jboss.deployment.subunit."jpa_core_EntityGraph_vehicles.ear"."jpa_core_EntityGraph_appmanaged_vehicle_client.jar".POST_MODULE: org.jboss.msc.service.StartException in service jboss.deployment.subunit."jpa_core_EntityGraph_vehicles.ear"."jpa_core_EntityGraph_appmanaged_vehicle_client.jar".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of subdeployment "jpa_core_EntityGraph_appmanaged_vehicle_client.jar" of deployment "jpa_core_EntityGraph_vehicles.ear"
        at org.jboss.as.server@26.0.0.Beta4//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:172)
        at org.jboss.msc@1.5.5.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1617)
        at org.jboss.msc@1.5.5.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1580)
        at org.jboss.msc@1.5.5.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1438)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NoClassDefFoundError: Failed to link com/sun/ts/tests/common/vehicle/VehicleClient (Module "deployment.jpa_core_EntityGraph_vehicles.ear.jpa_core_EntityGraph_appmanaged_vehicle_client.jar" from Service Module Loader): com/sun/ts/lib/harness/ServiceEETest
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1105)
        at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:351)
        at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:482)
        at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:276)
        at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:79)
        at org.jboss.modules.Module.loadModuleClass(Module.java:798)
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:192)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:408)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:396)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:115)
        at org.jboss.as.appclient@34.0.0.Beta1-SNAPSHOT//org.jboss.as.appclient.deployment.ApplicationClientManifestProcessor.deploy(ApplicationClientManifestProcessor.java:49)
        at org.jboss.as.server@26.0.0.Beta4//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:165)
        ... 8 more
Caused by: java.lang.ClassNotFoundException: com.sun.ts.lib.harness.ServiceEETest
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at org.jboss.modules.Utils.getSystemClass(Utils.java:179)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:393)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:115)
        ... 22 more

```
